In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# Loading the dataset
credit_card = pd.read_csv('/content/drive/My Drive/w1790011_FYP_6COSC023W.Y2023/Data Set/credit_card_default_payments_cleaned_data_set.csv')
print(credit_card.columns)

Index(['Unnamed: 0', 'Product Age in Months', 'Age', 'Product', 'Gender',
       'Limit', 'Gross Income', 'DPD Group', 'Credit Segment',
       'Settler and Revolver', 'Retail Segment', 'Employment Status',
       'Nature of Business', 'Application Score', 'Total OS Month N',
       'Spend Month N', 'Spend Month N-1', 'Spend Month N-2',
       'Payment Month N', 'Payment Month N-1', 'Payment Month N-2',
       'Int Month N', 'Int Month N-1', 'Int Month N-2', 'Method Month N',
       'Method Month N-1', 'Method Month N-2', 'Payment Default in Month N+1'],
      dtype='object')


In [4]:
#Load the Model File
import pickle
model_x = pickle.load(open('/content/drive/My Drive/w1790011_FYP_6COSC023W.Y2023/Prediction Model/credit_card_finalized_model.sav', 'rb'))

In [5]:
#Test the model using sample of default customer
predictionProbability = model_x.predict_proba([[82, 39, 130000, 1590000,1, 2, 119047, 0, 0, 0, 3500, 4000, 3136, 1843, 1885, 1848]])
prediction = model_x.predict([[82, 39, 130000, 1590000,1, 2, 119047, 0, 0, 0, 3500, 4000, 3136, 1843, 1885, 1848 ]])
print('Probability:', predictionProbability)
print('Probability %:', predictionProbability*100)
print('Prediction:', prediction)

Probability: [[0.01 0.99]]
Probability %: [[ 1. 99.]]
Prediction: [1]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [6]:
#Test the model using sample of non-default customer
predictionProbability = model_x.predict_proba([[108, 40, 128000, 4425000, 2, 2, 127360, 7351, 0, 0, 260, 20000, 0, 43, 0, 8]])
prediction = model_x.predict([[108, 40, 128000, 4425000, 2, 2, 127360, 7351, 0, 0, 260, 20000, 0, 43, 0, 8]])
print('Probability:', predictionProbability)
print('Probability %:', predictionProbability*100)
print('Prediction:', prediction)

Probability: [[0.75 0.25]]
Probability %: [[75. 25.]]
Prediction: [0]


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [7]:
#Test the model using large sample of customer data
sampleData = credit_card[:1000]
sampleDataFeatures = np.asarray(sampleData.drop(['Payment Default in Month N+1', 'Unnamed: 0', 'Nature of Business','Credit Segment','Method Month N-1','Method Month N','Application Score','Product','Method Month N-2','Employment Status','Gender','Retail Segment'], axis=1))
print(sampleDataFeatures)

predictionProbability = model_x.predict_proba(sampleDataFeatures)
prediction = model_x.predict(sampleDataFeatures)
print('Probability:', predictionProbability)
print('Probability %:', predictionProbability*100)
print('Prediction:', prediction)


[[1.390e+02 6.200e+01 2.250e+06 ... 0.000e+00 0.000e+00 3.896e+03]
 [1.260e+02 4.000e+01 2.700e+06 ... 0.000e+00 0.000e+00 0.000e+00]
 [1.740e+02 3.600e+01 1.260e+06 ... 0.000e+00 0.000e+00 0.000e+00]
 ...
 [2.300e+02 3.800e+01 1.020e+05 ... 2.950e+02 3.030e+02 2.870e+02]
 [2.290e+02 6.400e+01 1.810e+05 ... 1.462e+03 1.441e+03 1.403e+03]
 [2.290e+02 6.400e+01 1.848e+06 ... 0.000e+00 0.000e+00 0.000e+00]]
Probability: [[0.85 0.15]
 [0.   1.  ]
 [0.81 0.19]
 ...
 [0.04 0.96]
 [0.33 0.67]
 [0.96 0.04]]
Probability %: [[ 85.  15.]
 [  0. 100.]
 [ 81.  19.]
 ...
 [  4.  96.]
 [ 33.  67.]
 [ 96.   4.]]
Prediction: [0 1 0 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 0 1 1 1
 0 1 1 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1
 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 1 1 0 1 1 1 1
 1 1 1 1 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 0 1
 1 1 1 0 

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
